name: photographic_viewer
description: Photographic viewer for Desktop(Mac or Linux)

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.5
  exif: ^3.1.2
  share_plus: ^6.3.0
  path: ^1.8.2
  collection: ^1.17.0
  flutter_native_drag_n_drop: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
